### ISSUE TITLE
drvLEDs development

### ISSUE THREAD

**Issue by AksonovSergei** [AksonovSergei/NureEmbClass_2016#1]
drvLEDs should be developed.

You have to create branch and perform development in this one. 
Please do not merge you results in the trunk. I am going to do this in class together when all SW items will be ready.

**Comment by AksonovSergei** [comment]
Do not create branch now. We will discus this tomorrow in the class.

**Comment by NikolaiGerasimenko** [comment]
I renamed the driver into the drvLED.
