### ISSUE TITLE
drvKeyboard development

### ISSUE THREAD

**Issue by AksonovSergei** [AksonovSergei/NureEmbClass_2016#3]

**Comment by KostiantynAndrieiev** [comment]
Code is here on GitHub. Though it's a bit not optimized, but I'll fix it this night.

**Comment by KostiantynAndrieiev** [comment]
It contains simple elimination of contact bounce (by means of counters) and 1 method returning the key state.

**Comment by KostiantynAndrieiev** [comment]
Driver is optimized.
